name: 'Release'

# 触发条件：当你推送格式为 v*.*.* 的标签时自动运行，比如 v1.0.0
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create-release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-22.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    outputs:
      release_id: ${{ steps.create-release.outputs.id }}

    steps:
      - uses: actions/checkout@v4
      - name: 创建 GitHub Release
        id: create-release
        uses: tauri-apps/tauri-action@v0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # 不在此步骤进行构建，只创建 Release
          skipBuild: true
          tagName: ${{ github.ref_name }}
          releaseName: ${{ github.ref_name }}
          releaseBody: "自动发布 Tauri 应用版本 ${{ github.ref_name }}，请下载对应平台的安装包。"
          draft: true
          prerelease: false

